# Generated by Django 6.0.3 on 2026-05-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='resume_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
