# Generated by Django 6.0.3 on 2026-05-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commentaire_resume_ia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='resume_ia',
        ),
        migrations.AddField(
            model_name='article',
            name='resume_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
